application: shcms
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on
- datastore_admin: on
- remote_api: on

handlers:
  
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/vnd.microsoft.icon

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static
  
- url: /.*
  script: main.py
